## Introduction : Transformers

### Modeles

Hugging Face : GPT2

### Evaluation

- BLEU/ROUGE Score
- BERT Score

### Bechmark

| Modèle                                | BLEU Score | ROUGE-L Score | BERTScore |
|---------------------------------------|------------|----------------|-----------|
| **GPT-2**          | 0.0115     | 0.0952         | 0.8339    |
| **GPT-2 AventIQ**                     | 0.0047     | 0.1063         | 0.8294    |
| **DistilGPT2 yroshan**                     | 0.0033     | 0.0972         |  0.8278    |

## Common code

In [1]:
import pandas as pd
from datasets import Dataset, DatasetDict
from transformers import GPT2Tokenizer, GPT2LMHeadModel, Trainer, TrainingArguments, DataCollatorForLanguageModeling
import re

/home/rickgao/miniconda3/envs/tf-wsl/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2025-05-09 17:21:46.377434: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-05-09 17:21:46.377497: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-05-09 17:21:46.380099: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-05-09 17:21:46.637648: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-05-09 17:21:48.475503: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [2]:
# Load dataset and preprocess
df = pd.read_csv("MovieDataThread.csv")
df = df.dropna(subset=["Script"])
df = df.sample(n=1000, random_state=42)

In [3]:
from sklearn.model_selection import train_test_split

# Split the dataset into training and testing sets
train_texts, test_texts = train_test_split(df["Script"].tolist(), test_size=0.2, random_state=42)
dataset = DatasetDict({
    "train": Dataset.from_dict({"Script": train_texts}),
    "test": Dataset.from_dict({"Script": test_texts})
})

## Hugging face Transformer (GPT2)

https://huggingface.co/openai-community/gpt2

### Model

In [5]:
# Load the tokenizer and model from Hugging Face (GPT2)
model_name = "gpt2"
tokenizer = GPT2Tokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
model = GPT2LMHeadModel.from_pretrained(model_name)

In [6]:
def preprocess_text(text):
    text = re.sub(r"\n+", "\n", text)
    text = text.replace("\n", " NEWLINE_TOKEN ")
    text = re.sub(r"\s+", " ", text)
    return text.strip()

def tokenize_function(example):
    processed = [preprocess_text(script) for script in example["Script"]]
    encodings = tokenizer(processed, truncation=True, padding="longest", max_length=256)
    encodings["labels"] = encodings["input_ids"].copy()
    return encodings


tokenized_dataset = dataset.map(tokenize_function, batched=True, remove_columns=["Script"])
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

Parameter 'function'=<function tokenize_function at 0x7f4a02ac5a60> of the transform datasets.arrow_dataset.Dataset._map_single couldn't be hashed properly, a random hash was used instead. Make sure your transforms and parameters are serializable with pickle or dill for the dataset fingerprinting and caching to work. If you reuse this transform, the caching mechanism will consider it to be different from the previous calls and recompute everything. This warning is only showed once. Subsequent hashing failures won't be showed.
100%|██████████| 1/1 [01:06<00:00, 66.77s/ba]
100%|██████████| 1/1 [00:16<00:00, 16.97s/ba]

### Train

In [8]:
# Train the model (Arguments)
training_args = TrainingArguments(
    output_dir="./gpt2-script",
    eval_strategy="epoch",
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    num_train_epochs=10,
    logging_dir="./logs",
)

In [9]:
# Initialize the Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["test"],
    tokenizer=tokenizer,
    data_collator=data_collator
)

/tmp/ipykernel_1635/4126412472.py:2: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [10]:
# Train the model
trainer.train()

# Save the model
trainer.save_model("./gpt2-script")

`loss_type=None` was set in the config but it is unrecognised.Using the default loss: `ForCausalLMLoss`.

### Load model

In [57]:
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
from nltk.tokenize import word_tokenize
from rouge import Rouge
import re
import string

def calculate_bleu(reference, candidate):
    """
    Calculate BLEU score (it measures the similarity between two sentences)
    :param reference: The reference sentence
    :param candidate: The candidate sentence
    :return: The BLEU score
    """
    smoothing_function = SmoothingFunction().method4
    bleu_score = sentence_bleu([reference], candidate, smoothing_function=smoothing_function)
    return bleu_score

def calculate_rouge(reference, candidate):
    """
    Calculate ROUGE-L score (it calculates the longest common subsequence)
    :param reference: The reference sentence
    :param candidate: The candidate sentence
    :return: The ROUGE score
    """
    rouge = Rouge()
    scores = rouge.get_scores(candidate, reference)
    return scores[0]['rouge-l']['f']

def preprocess_text(text):
    """
    Preprocess the text by removing punctuation and converting to lowercase
    :param text: The input text
    :return: The preprocessed text
    """
    text = re.sub(f"[{re.escape(string.punctuation)}]", "", text)
    text = text.lower()
    return text

def calculate_scores(reference, candidate):
    """
    Calculate BLEU and ROUGE scores for the given reference and candidate sentences
    :param reference: The reference sentence
    :param candidate: The candidate sentence
    :return: The BLEU and ROUGE scores
    """
    # Preprocess the text
    reference = preprocess_text(reference)
    candidate = preprocess_text(candidate)

    reference_tokens = word_tokenize(reference)
    candidate_tokens = word_tokenize(candidate)

    bleu_score = calculate_bleu(reference_tokens, candidate_tokens)
    rouge_score = calculate_rouge(reference, candidate)

    return bleu_score, rouge_score

In [58]:
from transformers import GPT2Tokenizer, GPT2LMHeadModel, Trainer, TrainingArguments, DataCollatorForLanguageModeling
import evaluate
from bert_score import BERTScorer

# Load the model for evaluation
model = GPT2LMHeadModel.from_pretrained("./gpt2-script")
tokenizer = GPT2Tokenizer.from_pretrained("./gpt2-script")


def generate_text(prompt, max_new_tokens=100):
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    outputs = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=True,
        temperature=0.7,
        top_k=50,
        top_p=0.95,
        pad_token_id=tokenizer.eos_token_id
    )
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

### Evaluation

In [59]:
import re

def script_tokenize(text):
    text = re.sub(r"\n+", "\n", text)
    text = re.sub(r"\n", " NEWLINE_TOKEN ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip().split()

def custom_tokenize(text):
    first_tokenize = script_tokenize(text)
    entokenized = " ".join(first_tokenize)

    second_tokenize = word_tokenize(entokenized)
    return second_tokenize

In [ ]:
bleu_scores, rouge_scores = [], []
bert_f1, bert_precision, bert_recall = [], [], []


# Augment the SCRIPT_LIMIT_TOKEN_SIZE for better BERT Scores
SCRIPT_LIMIT_TOKEN_SIZE = 300
GENERATE_LIMIT_TOKEN_SIZE = 50

total = len(test_texts)
i = 1

scorer = BERTScorer(lang="en", model_type="roberta-base", rescale_with_baseline=True)

print("Evaluating the model on the test set...")
for full_text in test_texts:
    print(f"Evaluating {i}/{total}...")

    tokenized = tokenizer(full_text, return_tensors="pt", truncation=True,
                          max_length=SCRIPT_LIMIT_TOKEN_SIZE + GENERATE_LIMIT_TOKEN_SIZE)
    input_ids = tokenized.input_ids[0]

    if len(input_ids) <= SCRIPT_LIMIT_TOKEN_SIZE:
        i += 1
        continue

    seed_input_ids = input_ids[:SCRIPT_LIMIT_TOKEN_SIZE]
    expected_output_ids = input_ids[SCRIPT_LIMIT_TOKEN_SIZE:SCRIPT_LIMIT_TOKEN_SIZE + GENERATE_LIMIT_TOKEN_SIZE]

    seed_text = tokenizer.decode(seed_input_ids, skip_special_tokens=True)
    seed_text = custom_tokenize(seed_text)
    seed_text = " ".join(seed_text)
    
    reference_text = tokenizer.decode(expected_output_ids, skip_special_tokens=True).strip()
    reference_text = custom_tokenize(reference_text)
    reference_text = " ".join(reference_text)

    generated_text = generate_text(seed_text, max_new_tokens=GENERATE_LIMIT_TOKEN_SIZE)
    generated_text = re.sub(r"\s+", " ", generated_text).strip()
    generated_text = custom_tokenize(generated_text)
    generated_text = " ".join(generated_text)[len(seed_text) + 1:]

    candidate = generated_text
    reference = reference_text

    print(f"Seed: {seed_text}")
    print(f"Candidate: {candidate}")
    print(f"Reference: {reference}")
    
    bleu_score, rouge_score = calculate_scores(reference, candidate)

    P, R, F1 = scorer.score([candidate], [reference])
    f1_score = F1.mean().item()
    precision_score = P.mean().item()
    recall_score = R.mean().item()

    bleu_scores.append(bleu_score)
    rouge_scores.append(rouge_score)
    bert_f1.append(f1_score)
    bert_precision.append(precision_score)
    bert_recall.append(recall_score)

    print(f"BLEU score: {bleu_score}")
    print(f"ROUGE score: {rouge_score}")
    print(f"BERT F1 score: {f1_score}")
    print(f"BERT Precision score: {precision_score}")
    print(f"BERT Recall score: {recall_score}")

    with open(f"transformers-GPT2-{SCRIPT_LIMIT_TOKEN_SIZE}-{GENERATE_LIMIT_TOKEN_SIZE}.csv", "a") as f:
        f.write(f"{seed_text};{candidate};{reference};{bleu_score};{rouge_score};{f1_score};{precision_score};{recall_score}\n")

    i += 1

# Final scores
print(f"Average BLEU score : {sum(bleu_scores) / len(bleu_scores):.6f}")
print(f"Average ROUGE score : {sum(rouge_scores) / len(rouge_scores):.6f}")
print(f"Average BERT F1 score : {sum(bert_f1) / len(bert_f1):.6f}")
print(f"Average BERT Precision score : {sum(bert_precision) / len(bert_precision):.6f}")
print(f"Average BERT Recall score : {sum(bert_recall) / len(bert_recall):.6f}")

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Evaluating the model on the test set...
Evaluating 1/200...
Seed: 1 NEWLINE_TOKEN Delhi flight ! NEWLINE_TOKEN Sorry , Ma'am . NEWLINE_TOKEN Boarding is closed . NEWLINE_TOKEN Listen , I know ! NEWLINE_TOKEN I am so sorry , I got delayed . NEWLINE_TOKEN Just do something . NEWLINE_TOKEN Please help me . NEWLINE_TOKEN Sorry , Ma'am . NEWLINE_TOKEN You should have been on time . NEWLINE_TOKEN I know , I am so sorry ! NEWLINE_TOKEN I got stuck in traffic . NEWLINE_TOKEN You know how it is . NEWLINE_TOKEN Just , please ! Can you do this ? NEWLINE_TOKEN Okay , hold on . NEWLINE_TOKEN Thank you . NEWLINE_TOKEN Window seat , please . NEWLINE_TOKEN Excuse me . NEWLINE_TOKEN `` Oh you ! '' NEWLINE_TOKEN `` Oh you ! '' NEWLINE_TOKEN `` Entry to Delhi . '' NEWLINE_TOKEN `` Oh you ! Entry to Delhi . '' NEWLINE_TOKEN `` Oh you ! Entry to Delhi . Oh welcome . '' NEWLINE_TOKEN `` Delhi is fantastic . NEWLINE_TOKEN Delhi is wonderful . '' NEWLINE_TOKEN `` Delhi is jovial . NEWLINE_TOKEN Delhi is fun loving . '' NEWLINE_TOKEN `` It is filled with dreams . NEWLINE_TOKEN It is filled with kin . '' NEWLINE_TOKEN `` It is in my heart . NEWLINE_TOKEN Delhi is my life . '' NEWLINE_TOKEN `` Friends , it belongs to everyone . NEWLINE_TOKEN It will mesmerize you . '' NEWLINE_TOKEN `` It will mesmerize you . '' NEWLINE_TOKEN - It is really wonderful . NEWLINE_TOKEN `` Oh you ! Entry to Delhi . '' NEWLINE_TOKEN `` Oh you ! '' NEWLINE_TOKEN `` Oh you ! Entry to Delhi . '' NEWLINE_TOKEN `` Oh you ! Entry to Delhi . '' NEWLINE_TOKEN `` Oh you ! '' NEWLINE_TOKEN Ma'am ! Excuse me . NEWLINE_TOKEN Ma'am ! We have arrived in Delhi . NEWLINE_TOKEN Oh , yes , thanks
Candidate: . NEWLINE_TOKEN It is great ! NEWLINE_TOKEN It is a pleasure ! NEWLINE_TOKEN It is a pleasure ! NEWLINE_TOKEN It is a pleasure ! NEWLINE_TOKEN It is a pleasure !
Reference: . NEWLINE_TOKEN Hello , Twinkle . NEWLINE_TOKEN I have arrived in Delhi . NEWLINE_TOKEN Listen to me , was my wallet NEWLINE_TOKEN in the house ? NEWLINE_TOKEN God ! All my cards are NEWLINE_TOKEN at home , too . NEWLINE_TOKEN All the extra cash mom NEWLINE_TOKEN gave me is
BLEU score: 0.008999353981460421
ROUGE score: 0.11764705591695508
BERT F1 score: 0.360856831073761
BERT Precision score: 0.41670915484428406
BERT Recall score: 0.3049139976501465
Evaluating 2/200...
Seed: He 's going to end corruption . NEWLINE_TOKEN Gannu is here to rule . NEWLINE_TOKEN He 's going to end corruption . NEWLINE_TOKEN Gannu is here to rule . NEWLINE_TOKEN He 's going to end corruption . NEWLINE_TOKEN Gannu is here to rule . NEWLINE_TOKEN He 's going to end corruption . NEWLINE_TOKEN Calm down . NEWLINE_TOKEN Please calm down ! NEWLINE_TOKEN Please calm down ! NEWLINE_TOKEN This is not just you speaking up . NEWLINE_TOKEN It is the entire nation revolting ... NEWLINE_TOKEN against its pathetic plight . NEWLINE_TOKEN But the time has changed now , NEWLINE_TOKEN because the ultimate solution NEWLINE_TOKEN to all problems is now in our hands . NEWLINE_TOKEN And this solution , under my leadership NEWLINE_TOKEN will be provided for free to everyone . NEWLINE_TOKEN All the tyrants better watch out . NEWLINE_TOKEN Gannu the great has arrived ! NEWLINE_TOKEN In the rough waters of politics NEWLINE_TOKEN Gannu drops a bomb NEWLINE_TOKEN In the rough waters of politics NEWLINE_TOKEN Gannu drops a bomb NEWLINE_TOKEN Everyone will receive free whiskey NEWLINE_TOKEN Moonshine and rum NEWLINE_TOKEN Bloody hell . NEWLINE_TOKEN Oh God ! NEWLINE_TOKEN Please save me today . NEWLINE_TOKEN I swear to never drink again . NEWLINE_TOKEN Boss ! NEWLINE_TOKEN You mixed up your drinks last night . NEWLINE_TOKEN After whiskey you even NEWLINE_TOKEN gulped the watchman 's rum . NEWLINE_TOKEN Oh God ! NEWLINE_TOKEN Please save me today . NEWLINE_TOKEN I swear I 'll never mix my drinks again . NEWLINE_TOKEN Boss , your wife visited this morning . NEWLINE_TOKEN - Wake up , Prakash ! NEWLINE_TOKEN - What ? NEWLINE_TOKEN Boss has asked us to come home with him . NEWLINE_TOKEN Hurry up
Candidate: ! NEWLINE_TOKEN Hurry up ! NEWLINE_TOKEN Are you all right ? NEWLINE_TOKEN Yes ! NEWLINE_TOKEN Why ? NEWLINE_TOKEN What is it ? NEWLINE_TOKEN Why did
Reference: . NEWLINE_TOKEN Damn you . NEWLINE_TOKEN Bro , wake up ! NEWLINE_TOKEN Sister-in-law had NEWLINE_TOKEN come here this morning . NEWLINE_TOKEN We have to go home . NEWLINE_TOKEN - Sister-in-law ... this early ? NEWLINE_TOKEN - Yup . NEWLINE_TOKEN Phans
BLEU score: 0.025959210578187484
ROUGE score: 0.12121211643709846
BERT F1 score: 0.46628719568252563
BERT Precision score: 0.5625381469726562
BERT Recall score: 0.3725769519805908
Evaluating 3/200...
Seed: Come on , I 'm open ! NEWLINE_TOKEN Naty , over here ! NEWLINE_TOKEN Give me that . NEWLINE_TOKEN We were just ... NEWLINE_TOKEN Pass ! NEWLINE_TOKEN Here ! Over here ! NEWLINE_TOKEN Is someone else NEWLINE_TOKEN gon na turn Priscilla ? NEWLINE_TOKEN Me , too ! I 'm open ! NEWLINE_TOKEN Come on , I 'm open ! NEWLINE_TOKEN Pass it ! NEWLINE_TOKEN Amanda , here ! NEWLINE_TOKEN How about Wes ? NEWLINE_TOKEN How 's he doing ? NEWLINE_TOKEN He 's still Wes . NEWLINE_TOKEN He has no friends , really . NEWLINE_TOKEN Just kind of on his own world . NEWLINE_TOKEN I wish he played a sport . NEWLINE_TOKEN But he does n't want to . NEWLINE_TOKEN I know that . I was just saying . NEWLINE_TOKEN - I wish he did . NEWLINE_TOKEN - Well , stop . NEWLINE_TOKEN Why do you keep forcing that ? NEWLINE_TOKEN No , I 'm not forcing it ... NEWLINE_TOKEN I 'm ... NEWLINE_TOKEN just expressing a desire NEWLINE_TOKEN shared by many fathers NEWLINE_TOKEN to see my son NEWLINE_TOKEN do something athletic , NEWLINE_TOKEN which I expressed NEWLINE_TOKEN because I was told NEWLINE_TOKEN that 's what we do here . NEWLINE_TOKEN - Express . Safely . NEWLINE_TOKEN - Sorry . NEWLINE_TOKEN Okay , sorry . NEWLINE_TOKEN And Becca ? NEWLINE_TOKEN Um , she 's walking on air . NEWLINE_TOKEN She just got accepted NEWLINE_TOKEN into two different programs NEWLINE_TOKEN at Northwestern NEWLINE_TOKEN over spring break so ... NEWLINE_TOKEN - Fantastic ! NEWLINE_TOKEN - Yeah . NEWLINE_TOKEN Except the 1,200 dollars NEWLINE_TOKEN of cost that we do n't have . NEWLINE_TOKEN Yeah . NEWLINE_TOKEN Ballet and Computer Science . NEWLINE_TOKEN But she has to choose one so ... NEWLINE_TOKEN We 're hoping NEWLINE_TOKEN that she
Candidate: 's as good as NEWLINE_TOKEN with a smile on her face . NEWLINE_TOKEN OK , well . NEWLINE_TOKEN You 'll be in her NEWLINE_TOKEN for the dance . NEWLINE_TO
Reference: chooses ballet , NEWLINE_TOKEN that 's what she wants to do , NEWLINE_TOKEN ai n't it ? NEWLINE_TOKEN Yeah , I just , she just gives NEWLINE_TOKEN herself so much shit . NEWLINE_TOKEN For the other girls in the class NEWLINE_TOKEN being so much taller NEWLINE_TOKEN and thinner .
BLEU score: 0.032513248393194444
ROUGE score: 0.1568627403306422
BERT F1 score: 0.40564200282096863
BERT Precision score: 0.4426785111427307
BERT Recall score: 0.36788126826286316
Evaluating 4/200...
Seed: 1 NEWLINE_TOKEN [ ambient music ] NEWLINE_TOKEN [ audience applauding ] NEWLINE_TOKEN Here in New York , NEWLINE_TOKEN there 's a big election tomorrow . NEWLINE_TOKEN The city will be choosing NEWLINE_TOKEN a new mayor that many ... NEWLINE_TOKEN [ audience cheering ] NEWLINE_TOKEN ... that many are calling NEWLINE_TOKEN `` Not Bill de Blasio . '' NEWLINE_TOKEN [ audience laughs ] NEWLINE_TOKEN New York will also be electing NEWLINE_TOKEN a new city council , NEWLINE_TOKEN and there 's some shocking news NEWLINE_TOKEN out of that race . NEWLINE_TOKEN Manhattan candidate NEWLINE_TOKEN Zack Weiner -- NEWLINE_TOKEN -Weiner ? NEWLINE_TOKEN - '' Winer . '' NEWLINE_TOKEN -Weiner . NEWLINE_TOKEN - [ chanting ] Weiner ! NEWLINE_TOKEN The whole incident NEWLINE_TOKEN was so humiliating ... NEWLINE_TOKEN I feel kind of , you know , bad NEWLINE_TOKEN for him that that 's published . NEWLINE_TOKEN [ all laughing ] NEWLINE_TOKEN [ man ] NEWLINE_TOKEN What the hell am I looking at ? NEWLINE_TOKEN [ man ] Weiner ! NEWLINE_TOKEN -Who is Zack Weiner ? NEWLINE_TOKEN -Zack Weiner . NEWLINE_TOKEN -Zack Weiner . NEWLINE_TOKEN -Zack Weiner . NEWLINE_TOKEN -His name is Zack Weiner . NEWLINE_TOKEN -Weiner . NEWLINE_TOKEN -Weiner . NEWLINE_TOKEN -Zack Weiner . NEWLINE_TOKEN Zack Weiner ! NEWLINE_TOKEN [ all chanting ] NEWLINE_TOKEN Weiner ! Weiner ! Weiner ! NEWLINE_TOKEN Weiner ! Weiner ! Weiner ! NEWLINE_TOKEN [ The Place to Be '' by Ernest NEWLINE_TOKEN Ernie & The Sincerities ] NEWLINE_TOKEN Whoo NEWLINE_TOKEN Yeah NEWLINE_TOKEN I welcome you , NEWLINE_TOKEN my little ingenue NEWLINE_TOKEN To a place NEWLINE_TOKEN where you can start anew NEWLINE_TOKEN Where the people NEWLINE_TOKEN are
Candidate: going to be able to make their own decisions NEWLINE_TOKEN And where NEWLINE_TOKEN you can actually have a say NEWLINE_TOKEN about who gets to run NEWLINE_TOKEN What the hell is the legal NEWLINE
Reference: comin ' and goin ' NEWLINE_TOKEN 'Cause everywhere you go NEWLINE_TOKEN is open NEWLINE_TOKEN Said the city 's NEWLINE_TOKEN the place to be NEWLINE_TOKEN It 's got everything , NEWLINE_TOKEN everything NEWLINE_TOKEN And the city 's NEWLINE_TOKEN the place to be , yeah
BLEU score: 0.029148297779617756
ROUGE score: 0.20833332841145846
BERT F1 score: 0.2830350995063782
BERT Precision score: 0.29293832182884216
BERT Recall score: 0.27160143852233887
Evaluating 5/200...
Seed: Moving onto the Hollywood Freeway , NEWLINE_TOKEN we have a multiple vehicle ... NEWLINE_TOKEN multiple injury accident . NEWLINE_TOKEN An absolute mess NEWLINE_TOKEN from VineStreet to the valley . NEWLINE_TOKEN If you 're in it , NEWLINE_TOKEN expect a long commute . NEWLINE_TOKEN If you 're not , NEWLINE_TOKEN seek alternate routes . NEWLINE_TOKEN If Dan doesn 't want to do a daily rate , NEWLINE_TOKEN we can talk about a weekly rate . NEWLINE_TOKEN But I 'm tellin ' you right now , NEWLINE_TOKEN I 'm not goin ' below a million . NEWLINE_TOKEN I mean , think about it . NEWLINE_TOKEN I 'm risking my reputation ... NEWLINE_TOKEN as the host NEWLINE_TOKEN of this country 's number-one ... NEWLINE_TOKEN nationally syndicated talk show to do NEWLINE_TOKEN a cameo in some cheap slasher flick . NEWLINE_TOKEN I mean , why ca n't these guys write me NEWLINE_TOKEN a fuckin ' decent part ? NEWLINE_TOKEN You know ? NEWLINE_TOKEN I lived through the fuckin ' thing . NEWLINE_TOKEN By the way , did you talk to Cathy NEWLINE_TOKEN about that Navy SEAL script ? NEWLINE_TOKEN Hang on a sec . NEWLINE_TOKEN - Hello ? NEWLINE_TOKEN - Hello ? NEWLINE_TOKEN - Who 's this ? NEWLINE_TOKEN - Who 's this ? NEWLINE_TOKEN - Who are you calling ? NEWLINE_TOKEN - Oh . You know what ? NEWLINE_TOKEN - I 'm sorry . I have the wrong number . NEWLINE_TOKEN - That 's okay . NEWLINE_TOKEN Wait a minute . I know your voice . NEWLINE_TOKEN You sound a lot like that guy on TV . NEWLINE_TOKEN Um , Cotton Weary . NEWLINE_TOKEN - I do , huh ? NEWLINE_TOKEN - Yeah . NEWLINE_TOKEN I think he 's got NEWLINE_TOKEN a really
Candidate: big voice . NEWLINE_TOKEN Oh . Oh . NEWLINE_TOKEN Oh . NEWLINE_TOKEN - Oh . NEWLINE_TOKEN - I 'm a little concerned about you . NEWLINE_TOKEN I 'm just
Reference: sexy voice . NEWLINE_TOKEN - Well , thank you . NEWLINE_TOKEN - Wait a minute . NEWLINE_TOKEN You are Cotton , are n't you ? NEWLINE_TOKEN Oh , my God . NEWLINE_TOKEN I am talking to Cotton Weary . NEWLINE_TOKEN I ca n't believe this . NEWLINE_TOKEN You got
BLEU score: 0.030295831737815616
ROUGE score: 0.22222221777777784
BERT F1 score: 0.5645368695259094
BERT Precision score: 0.6434720158576965
BERT Recall score: 0.48711109161376953
Evaluating 6/200...
Seed: And I 'll start it up ... NEWLINE_TOKEN ... and we 'll start generating . NEWLINE_TOKEN John has a very special mission in life . NEWLINE_TOKEN He is trying to contact aliens . NEWLINE_TOKEN It was started by myself . NEWLINE_TOKEN My grandfather helped me . NEWLINE_TOKEN I lived with my grandparents NEWLINE_TOKEN in a small cottage in Northern Michigan . NEWLINE_TOKEN I started building NEWLINE_TOKEN the electronic equipment to make contact NEWLINE_TOKEN with whatever might be out there NEWLINE_TOKEN beyond the Earth . NEWLINE_TOKEN It grew to encompass an entire bedroom . NEWLINE_TOKEN That equipment continued to grow . NEWLINE_TOKEN In the next two years , NEWLINE_TOKEN it was migrating into the living room . NEWLINE_TOKEN It became more and more massive . NEWLINE_TOKEN Most everything I did was self-taught . NEWLINE_TOKEN I envisioned an idea NEWLINE_TOKEN and completed that vision , NEWLINE_TOKEN built it into a physical reality . NEWLINE_TOKEN I was always seeking to explore , NEWLINE_TOKEN to look beyond what we have here . NEWLINE_TOKEN I pictured many alien worlds , NEWLINE_TOKEN imagining what it would be like NEWLINE_TOKEN to make contact . NEWLINE_TOKEN The moment of sharing extreme knowledge NEWLINE_TOKEN and thoughts NEWLINE_TOKEN and communication with another species , NEWLINE_TOKEN is just beyond anything NEWLINE_TOKEN most of us even imagine . NEWLINE_TOKEN I seem to be picking up a radio signal . NEWLINE_TOKEN Okay , fine . NEWLINE_TOKEN I decided that the best way NEWLINE_TOKEN to try and make contact NEWLINE_TOKEN was to broadcast a signal NEWLINE_TOKEN into outer space . NEWLINE_TOKEN I thought the best signal would be music . NEWLINE_TOKEN Technically , we were achieving NEWLINE_TOKEN the actual transmissions NEWLINE_TOKEN from a large tower out in front NEWLINE_TOKEN of mygrandparents ' home . NEWLINE_TOKEN I sent music
Candidate: over the radio . NEWLINE_TOKEN I thought it was going to be very powerful . NEWLINE_TOKEN It was . NEWLINE_TOKEN It was a signal from our planet NEWLINE_TOKEN that went from our planet NEW
Reference: into space NEWLINE_TOKEN because it represents NEWLINE_TOKEN a certain , uh , universal language . NEWLINE_TOKEN And I 'm talking NEWLINE_TOKEN about non-commercial music as such . NEWLINE_TOKEN I 'm talking about jazz , NEWLINE_TOKEN uh , electronic music ... NEWLINE_TOKEN Kraftwerk , Tangerine
BLEU score: 0.02313977361917772
ROUGE score: 0.0888888839111114
BERT F1 score: 0.3716423213481903
BERT Precision score: 0.4024968445301056
BERT Recall score: 0.3398178517818451
Evaluating 7/200...
Seed: 1 NEWLINE_TOKEN 'It is said that Heer and Ranjha NEWLINE_TOKEN made TakhtHazaare popular . ' NEWLINE_TOKEN 'Sohni-Mehiwal made NEWLINE_TOKEN river Chenab popular . ' NEWLINE_TOKEN 'Romeo and Juliet made Italy popular . ' NEWLINE_TOKEN 'But this is not Italy . NEWLINE_TOKEN This is Patiala , my city . ' NEWLINE_TOKEN 'Now even this will become NEWLINE_TOKEN popular in the entire world . ' NEWLINE_TOKEN 'Because of my love story . ' NEWLINE_TOKEN Laali , what are you doing dear ? NEWLINE_TOKEN Come now . NEWLINE_TOKEN Eat food . NEWLINE_TOKEN A person gets up on time , takes a bath , NEWLINE_TOKEN gets ready and goes to school . NEWLINE_TOKEN A person should do something on time . NEWLINE_TOKEN Late in everything . NEWLINE_TOKEN What is left behind now ? NEWLINE_TOKEN Do n't pamper him so much . NEWLINE_TOKEN He can at least food by himself . NEWLINE_TOKEN Laali . NEWLINE_TOKEN Is taking handkerchief so important ? NEWLINE_TOKEN -Eat food . NEWLINE_TOKEN -Mother , I am already late . NEWLINE_TOKEN The school is very strict . NEWLINE_TOKEN They will not let anyone NEWLINE_TOKEN enter school without handkerchief . NEWLINE_TOKEN Okay . NEWLINE_TOKEN Eat food properly . NEWLINE_TOKEN -I am already late . NEWLINE_TOKEN -At least eat food . NEWLINE_TOKEN Laali . NEWLINE_TOKEN Laali . NEWLINE_TOKEN Laali . NEWLINE_TOKEN Take your bag . NEWLINE_TOKEN Today he is not going to come . NEWLINE_TOKEN He has left you alone . NEWLINE_TOKEN That day is never going to NEWLINE_TOKEN come when he would leave me alone . NEWLINE_TOKEN Today is that day . NEWLINE_TOKEN Come on . Will you keep standing
Candidate: there ? NEWLINE_TOKEN Are you going to say something ? NEWLINE_TOKEN Are you going to sit down ? NEWLINE_TOKEN I am going to sit down . NEWLINE_TOKEN Okay . NEWLINE_TOKEN
Reference: here ? NEWLINE_TOKEN Come on we are getting late . NEWLINE_TOKEN -Come on . NEWLINE_TOKEN -Take care of your Frooti . NEWLINE_TOKEN Laali , slowly buddy . NEWLINE_TOKEN Take this and give me one cigarette . NEWLINE_TOKEN Laali . NEWLINE_TOKEN Laali , she has
BLEU score: 0.011356650187113671
ROUGE score: 0.10810810355003672
BERT F1 score: 0.4650895595550537
BERT Precision score: 0.5171777606010437
BERT Recall score: 0.4129434823989868
Evaluating 8/200...
Seed: Pay attention to the sights , NEWLINE_TOKEN and not the words . NEWLINE_TOKEN Because sounds can NEWLINE_TOKEN often be deceptive . NEWLINE_TOKEN But sight ... NEWLINE_TOKEN Sights never lie . NEWLINE_TOKEN So the question is not NEWLINE_TOKEN what is in front of your eyes . NEWLINE_TOKEN The question is what NEWLINE_TOKEN are you looking at ? NEWLINE_TOKEN David , my brother . NEWLINE_TOKEN How are you ? NEWLINE_TOKEN All good , man . NEWLINE_TOKEN Hand it over . NEWLINE_TOKEN Next time you got to be here earlier . NEWLINE_TOKEN You ca n't keep me waiting like this . NEWLINE_TOKEN You see , NEWLINE_TOKEN Tony , I want to leave this job . NEWLINE_TOKEN If I do n't leave this job , NEWLINE_TOKEN my wife will leave me . NEWLINE_TOKEN That 's a good thing . NEWLINE_TOKEN End of all your troubles . NEWLINE_TOKEN Let her go . Find yourself a new wife . NEWLINE_TOKEN You see , you ca n't NEWLINE_TOKEN keep changing jobs all the time . NEWLINE_TOKEN I apologise , but I really NEWLINE_TOKEN can not continue doing this . NEWLINE_TOKEN Tony . NEWLINE_TOKEN Tony . NEWLINE_TOKEN Give me my money , Tony . NEWLINE_TOKEN I need the money . NEWLINE_TOKEN You 'll get paid NEWLINE_TOKEN only after you make the next delivery . NEWLINE_TOKEN Understood . NEWLINE_TOKEN -Tony , please listen to me -- NEWLINE_TOKEN -Move ! NEWLINE_TOKEN Tony , I need the money . NEWLINE_TOKEN My family ... please give NEWLINE_TOKEN me my money , Tony . NEWLINE_TOKEN David ! NEWLINE_TOKEN David , stop . NEWLINE_TOKEN Stop . NEWLINE_TOKEN You brought the police ! NEWLINE_TOKEN You scum . NEWLINE_TOKEN I did n't bring anyone ! NEWLINE_TOKEN Stop . Stop . Stop . NEWLINE_TOKEN Catch him . Stop . NEWLINE_TOKEN Mary , open
Candidate: the door . NEWLINE_TOKEN Come on . NEWLINE_TOKEN Mary , open it . NEWLINE_TOKEN What is this ? NEWLINE_TOKEN You have brought the police ! NEWLINE_TOKEN What is this ?
Reference: the door . NEWLINE_TOKEN Coming . Hold on . NEWLINE_TOKEN Mary , open the door . NEWLINE_TOKEN -What -- NEWLINE_TOKEN -What took you so long ? NEWLINE_TOKEN What happened ? NEWLINE_TOKEN Pack your bags . NEWLINE_TOKEN We need to leave right now ! NEWLINE_TOKEN Go where ?
BLEU score: 0.10958877861485218
ROUGE score: 0.3999999953125
BERT F1 score: 0.6653649210929871
BERT Precision score: 0.7112108469009399
BERT Recall score: 0.619612991809845
Evaluating 9/200...

## TODO

- Augmenter l'epoch
- max_length=128 ou 256

## Hugging face Transformer (AventIQ)

https://huggingface.co/AventIQ-AI/gpt-2-movie-script-writter

In [37]:
from transformers import AutoTokenizer, AutoModelForCausalLM


# Load the tokenizer and model from Hugging Face (GPT2)
model_name = "AventIQ-AI/gpt-2-movie-script-writter"
tokenizer = GPT2Tokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
model = GPT2LMHeadModel.from_pretrained(model_name)

In [38]:
def preprocess_text(text):
    text = re.sub(r"\n+", "\n", text)
    text = text.replace("\n", " NEWLINE_TOKEN ")
    text = re.sub(r"\s+", " ", text)
    return text.strip()

def tokenize_function(example):
    processed = [preprocess_text(script) for script in example["Script"]]
    encodings = tokenizer(processed, truncation=True, padding="longest", max_length=256)
    encodings["labels"] = encodings["input_ids"].copy()
    return encodings

tokenized_dataset = dataset.map(tokenize_function, batched=True, remove_columns=["Script"])
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

100%|██████████| 1/1 [01:05<00:00, 65.99s/ba]
100%|██████████| 1/1 [00:16<00:00, 16.13s/ba]

### Train

In [42]:
# Train the model (Arguments)
training_args = TrainingArguments(
    output_dir="./aventiq-script",
    eval_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=1,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    num_train_epochs=10,
    logging_dir="./logs",
)

In [43]:
# Initialize the Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["test"],
    tokenizer=tokenizer,
    data_collator=data_collator
)

/tmp/ipykernel_1635/4126412472.py:2: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [44]:
# Train the model
trainer.train()

# Save the model
trainer.save_model("./aventiq-script")

In [45]:
from transformers import GPT2Tokenizer, GPT2LMHeadModel, Trainer, TrainingArguments, DataCollatorForLanguageModeling
import evaluate

# Load the model for evaluation
model = GPT2LMHeadModel.from_pretrained("./aventiq-script")
tokenizer = GPT2Tokenizer.from_pretrained("./aventiq-script")

# Generate text

def generate_text(prompt, max_new_tokens=100):
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    outputs = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=True,
        temperature=0.7,
        top_k=50,
        top_p=0.95,
        pad_token_id=tokenizer.eos_token_id
    )
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

### Evaluation

In [46]:
import re

def script_tokenize(text):
    text = re.sub(r"\n+", "\n", text)
    text = re.sub(r"\n", " NEWLINE_TOKEN ", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip().split()

def custom_tokenize(text):
    first_tokenize = script_tokenize(text)
    entokenized = " ".join(first_tokenize)

    second_tokenize = word_tokenize(entokenized)
    return second_tokenize

In [47]:
import re
from bert_score import BERTScorer

bleu_scores, rouge_scores = [], []
bert_f1, bert_precision, bert_recall = [], [], []

SCRIPT_LIMIT_TOKEN_SIZE = 50
GENERATE_LIMIT_TOKEN_SIZE = 50

total = len(test_texts)
i = 1

scorer = BERTScorer(lang="en", model_type="roberta-base", rescale_with_baseline=True)

print("Evaluating the model on the test set...")
for full_text in test_texts:
    print(f"Evaluating {i}/{total}...")

    tokenized = tokenizer(full_text, return_tensors="pt", truncation=True,
                          max_length=SCRIPT_LIMIT_TOKEN_SIZE + GENERATE_LIMIT_TOKEN_SIZE)
    input_ids = tokenized.input_ids[0]

    if len(input_ids) <= SCRIPT_LIMIT_TOKEN_SIZE:
        i += 1
        continue

    seed_input_ids = input_ids[:SCRIPT_LIMIT_TOKEN_SIZE]
    expected_output_ids = input_ids[SCRIPT_LIMIT_TOKEN_SIZE:SCRIPT_LIMIT_TOKEN_SIZE + GENERATE_LIMIT_TOKEN_SIZE]

    seed_text = tokenizer.decode(seed_input_ids, skip_special_tokens=True)
    seed_text = custom_tokenize(seed_text)
    seed_text = " ".join(seed_text)
    
    reference_text = tokenizer.decode(expected_output_ids, skip_special_tokens=True).strip()
    reference_text = custom_tokenize(reference_text)
    reference_text = " ".join(reference_text)

    generated_text = generate_text(seed_text, max_new_tokens=GENERATE_LIMIT_TOKEN_SIZE)
    generated_text = re.sub(r"\s+", " ", generated_text).strip()
    generated_text = custom_tokenize(generated_text)
    generated_text = " ".join(generated_text)[len(seed_text) + 1:]

    candidate = generated_text
    reference = reference_text

    print(f"Seed: {seed_text}")
    print(f"Candidate: {candidate}")
    print(f"Reference: {reference}")
    
    bleu_score, rouge_score = calculate_scores(reference, candidate)

    P, R, F1 = scorer.score([candidate], [reference])
    f1_score = F1.mean().item()
    precision_score = P.mean().item()
    recall_score = R.mean().item()

    bleu_scores.append(bleu_score)
    rouge_scores.append(rouge_score)
    bert_f1.append(f1_score)
    bert_precision.append(precision_score)
    bert_recall.append(recall_score)

    print(f"BLEU score: {bleu_score}")
    print(f"ROUGE score: {rouge_score}")
    print(f"BERT F1 score: {f1_score}")
    print(f"BERT Precision score: {precision_score}")
    print(f"BERT Recall score: {recall_score}")

    with open(f"transformers-aventIQ-{SCRIPT_LIMIT_TOKEN_SIZE}-{GENERATE_LIMIT_TOKEN_SIZE}.csv", "a") as f:
        f.write(f"{seed_text};{candidate};{reference};{bleu_score};{rouge_score};{f1_score};{precision_score};{recall_score}\n")

    i += 1

print(f"Average BLEU score : {sum(bleu_scores) / len(bleu_scores):.6f}")
print(f"Average ROUGE score : {sum(rouge_scores) / len(rouge_scores):.6f}")
print(f"Average BERT F1 score : {sum(bert_f1) / len(bert_f1):.6f}")
print(f"Average BERT Precision score : {sum(bert_precision) / len(bert_precision):.6f}")
print(f"Average BERT Recall score : {sum(bert_recall) / len(bert_recall):.6f}")

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Evaluating the model on the test set...
Evaluating 1/200...
Seed: 1 NEWLINE_TOKEN Delhi flight ! NEWLINE_TOKEN Sorry , Ma'am . NEWLINE_TOKEN Boarding is closed . NEWLINE_TOKEN Listen , I know ! NEWLINE_TOKEN I am so sorry , I got delayed . NEWLINE_TOKEN Just do something . NEWLINE_TOKEN Please help me . NEWLINE_TOKEN Sorry , Ma'am
Candidate: . NEWLINE_TOKEN Please help me . NEWLINE_TOKEN I have a daughter and she needs me . NEWLINE_TOKEN I have a beautiful son . NEWLINE_TOKEN He is very bright and cheerful . NEWLINE_
Reference: . NEWLINE_TOKEN You should have been on time . NEWLINE_TOKEN I know , I am so sorry ! NEWLINE_TOKEN I got stuck in traffic . NEWLINE_TOKEN You know how it is . NEWLINE_TOKEN Just , please ! Can you do this ? NEWLINE_TOKEN Okay , hold on . NEWLINE_TOKEN Thank
BLEU score: 0.04262595673022913
ROUGE score: 0.15999999528800013
BERT F1 score: 0.5058519840240479
BERT Precision score: 0.5406272411346436
BERT Recall score: 0.4704921245574951
Evaluating 2/200...
Seed: He 's going to end corruption . NEWLINE_TOKEN Gannu is here to rule . NEWLINE_TOKEN He 's going to end corruption . NEWLINE_TOKEN Gannu is here to rule . NEWLINE_TOKEN He 's going to end corruption . NEWLINE_TOKEN Gannu is here to rule .
Candidate: NEWLINE_TOKEN He 's going to end . NEWLINE_TOKEN You can bring the pigs back here . NEWLINE_TOKEN They won 't be happy . NEWLINE_TOKEN You can bring the pigs back here .
Reference: He 's going to end corruption . NEWLINE_TOKEN Calm down . NEWLINE_TOKEN Please calm down ! NEWLINE_TOKEN Please calm down ! NEWLINE_TOKEN This is not just you speaking up . NEWLINE_TOKEN It is the entire nation revolting ... NEWLINE_TOKEN against its pathetic plight . NEWLINE_TOKEN But the time
BLEU score: 0.09969655812901013
ROUGE score: 0.29166666197916674
BERT F1 score: 0.4452289342880249
BERT Precision score: 0.4658066928386688
BERT Recall score: 0.4236147999763489
Evaluating 3/200...
Seed: Come on , I 'm open ! NEWLINE_TOKEN Naty , over here ! NEWLINE_TOKEN Give me that . NEWLINE_TOKEN We were just ... NEWLINE_TOKEN Pass ! NEWLINE_TOKEN Here ! Over here ! NEWLINE_TOKEN Is someone else NEWLINE_TOKEN gon na turn Priscilla ? NEWLINE_TOKEN Me , too ! I
Candidate: 'm over here ! NEWLINE_TOKEN We were just kids , playin 'em NEWLINE_TOKEN when a man came over here . NEWLINE_TOKEN Shhh ! NEWLINE_TOKEN I don ' t know if
Reference: 'm open ! NEWLINE_TOKEN Come on , I 'm open ! NEWLINE_TOKEN Pass it ! NEWLINE_TOKEN Amanda , here ! NEWLINE_TOKEN How about Wes ? NEWLINE_TOKEN How 's he doing ? NEWLINE_TOKEN He 's still Wes . NEWLINE_TOKEN He has no friends , really . NEWLINE_TOKEN Just kind of on
BLEU score: 0.035459386019628426
ROUGE score: 0.19607842642060758
BERT F1 score: 0.44604653120040894
BERT Precision score: 0.415144145488739
BERT Recall score: 0.47611045837402344
Evaluating 4/200...
Seed: 1 NEWLINE_TOKEN [ ambient music ] NEWLINE_TOKEN [ audience applauding ] NEWLINE_TOKEN Here in New York , NEWLINE_TOKEN there 's a big election tomorrow . NEWLINE_TOKEN The city will be choosing NEWLINE_TOKEN a new mayor that many ... NEWLINE_TOKEN [ audience cheering ] NEWLINE_TOKEN ... that
Candidate: many people didn 't know about . NEWLINE_TOKEN [ Martin O'Malley ] The people of this city , NEWLINE_TOKEN they 're proud to have . NEWLINE_TOKEN The people of this city , they '
Reference: many are calling NEWLINE_TOKEN `` Not Bill de Blasio . '' NEWLINE_TOKEN [ audience laughs ] NEWLINE_TOKEN New York will also be electing NEWLINE_TOKEN a new city council , NEWLINE_TOKEN and there 's some shocking news NEWLINE_TOKEN out of that race . NEWLINE_TOKEN Manhattan candidate NEWLINE_TOKEN Zack Weiner --
BLEU score: 0.023703239389362182
ROUGE score: 0.19354838251821027
BERT F1 score: 0.3939679265022278
BERT Precision score: 0.37546229362487793
BERT Recall score: 0.41127052903175354
Evaluating 5/200...
Seed: Moving onto the Hollywood Freeway , NEWLINE_TOKEN we have a multiple vehicle ... NEWLINE_TOKEN multiple injury accident . NEWLINE_TOKEN An absolute mess NEWLINE_TOKEN from VineStreet to the valley . NEWLINE_TOKEN If you 're in it , NEWLINE_TOKEN expect a long commute . NEWLINE_TOKEN If you 're not ,
Candidate: NEWLINE_TOKEN expect a long commute . NEWLINE_TOKEN My sister and I both know NEWLINE_TOKEN that if we drive hard enough , NEWLINE_TOKEN we can get killed . NEWLINE_TOKEN If I
Reference: seek alternate routes . NEWLINE_TOKEN If Dan doesn 't want to do a daily rate , NEWLINE_TOKEN we can talk about a weekly rate . NEWLINE_TOKEN But I 'm tellin ' you right now , NEWLINE_TOKEN I 'm not goin ' below a million .
BLEU score: 0.08330028002939137
ROUGE score: 0.2592592544307271
BERT F1 score: 0.39866918325424194
BERT Precision score: 0.5149242281913757
BERT Recall score: 0.2865346074104309
Evaluating 6/200...
Seed: And I 'll start it up ... NEWLINE_TOKEN ... and we 'll start generating . NEWLINE_TOKEN John has a very special mission in life . NEWLINE_TOKEN He is trying to contact aliens . NEWLINE_TOKEN It was started by myself . NEWLINE_TOKEN My grandfather helped me . NEWLINE_TOKEN I lived with
Candidate: him ... NEWLINE_TOKEN ... when he was a kid . NEWLINE_TOKEN His name was Juana Garcia-Alves . NEWLINE_TOKEN And he was 11 when he started . NEWLINE_TOKEN I was his
Reference: my grandparents NEWLINE_TOKEN in a small cottage in Northern Michigan . NEWLINE_TOKEN I started building NEWLINE_TOKEN the electronic equipment to make contact NEWLINE_TOKEN with whatever might be out there NEWLINE_TOKEN beyond the Earth . NEWLINE_TOKEN It grew to encompass an entire bedroom . NEWLINE_TOKEN That equipment continued to grow .
BLEU score: 0.03462446249627717
ROUGE score: 0.15686274079200319
BERT F1 score: 0.33478572964668274
BERT Precision score: 0.34757480025291443
BERT Recall score: 0.32060903310775757
Evaluating 7/200...
Seed: 1 NEWLINE_TOKEN 'It is said that Heer and Ranjha NEWLINE_TOKEN made TakhtHazaare popular . ' NEWLINE_TOKEN 'Sohni-Mehiwal made NEWLINE_TOKEN river Chenab popular . ' NEWLINE_TOKEN 'Romeo and Juliet made Italy popular . ' NEWLINE_TOKEN
Candidate: 'The Romans made Rome popular . ' NEWLINE_TOKEN 'Hermann , Nietzsche , made Germany popular . NEWLINE_TOKEN 'Nietzsche , Strauss , made Germany popular . NEWLINE_TOKEN 'Guten Tag .
Reference: 'But this is not Italy . NEWLINE_TOKEN This is Patiala , my city . ' NEWLINE_TOKEN 'Now even this will become NEWLINE_TOKEN popular in the entire world . ' NEWLINE_TOKEN 'Because of my love story . ' NEWLINE_TOKEN Laali , what are you doing dear ?
BLEU score: 0.03697337514651725
ROUGE score: 0.17021276161158908
BERT F1 score: 0.33529555797576904
BERT Precision score: 0.3664884865283966
BERT Recall score: 0.30306512117385864
Evaluating 8/200...
Seed: Pay attention to the sights , NEWLINE_TOKEN and not the words . NEWLINE_TOKEN Because sounds can NEWLINE_TOKEN often be deceptive . NEWLINE_TOKEN But sight ... NEWLINE_TOKEN Sights never lie . NEWLINE_TOKEN So the question is not NEWLINE_TOKEN what is in front of your eyes . NEWLINE_TOKEN The question is
Candidate: who shall NEWLINE_TOKEN see it first . NEWLINE_TOKEN Who shall NEWLINE_TOKEN behold it first ? NEWLINE_TOKEN Who shall NEWLINE_TOKEN whisper it to you ? NEWLINE_TOKEN Who
Reference: what NEWLINE_TOKEN are you looking at ? NEWLINE_TOKEN David , my brother . NEWLINE_TOKEN How are you ? NEWLINE_TOKEN All good , man . NEWLINE_TOKEN Hand it over . NEWLINE_TOKEN Next time you got to be here earlier . NEWLINE_TOKEN You ca n't keep me waiting like this .
BLEU score: 0.033547070989359294
ROUGE score: 0.22222221831111116
BERT F1 score: 0.38868552446365356
BERT Precision score: 0.4578765630722046
BERT Recall score: 0.3201346695423126
Evaluating 9/200...
Seed: This is my recurring dream NEWLINE_TOKEN That I am fIying .. NEWLINE_TOKEN .. Iike a bird .. in the sky NEWLINE_TOKEN Cutting through the cIouds NEWLINE_TOKEN And when I am fIying .. I feeI happy NEWLINE_TOKEN A happiness that is NEWLINE_TOKEN
Candidate: all but certain NEWLINE_TOKEN When the birds sing and the bees dance NEWLINE_TOKEN And when the bees die I NEWLINE_TOKEN Wait till the cIouds NEWLINE_TOKEN That I will be avenge
Reference: impossibIe to describe NEWLINE_TOKEN A feeIing Iike nothing NEWLINE_TOKEN eIse - Unique ... wondrous NEWLINE_TOKEN But this is not a dream- this is reaI NEWLINE_TOKEN The wind that caresses my face NEWLINE_TOKEN The sound of g
BLEU score: 0.01076706214549613
ROUGE score: 0.03999999507200061
BERT F1 score: 0.30004554986953735
BERT Precision score: 0.3316482603549957
BERT Recall score: 0.26734280586242676
Evaluating 10/200...
Seed: [ EERIE MUSIC PLAYING ] NEWLINE_TOKEN [ KNOCKING ON DOOR ] NEWLINE_TOKEN [ LANDLORD ] Father ! NEWLINE_TOKEN [ KNOCKING ON DOOR ] NEWLINE_TOKEN [ LANDLORD ] NEWLINE_TOKEN Open the door , Father ! NEWLINE_TOKEN [
Candidate: SUSPENSEFUL HORSES ] NEWLINE_TOKEN Door open , NEWLINE_TOKEN mother ! NEWLINE_TOKEN [ KNOCKING ON DOOR ] NEWLINE_TOKEN [ SUSPENSEFUL HORS
Reference: BANGING ON DOOR ] NEWLINE_TOKEN [ LANDLORD ] Father ! NEWLINE_TOKEN Father ! NEWLINE_TOKEN [ DOOR RATTLING ] NEWLINE_TOKEN [ LANDLORD ] My god ! NEWLINE_TOKEN [ BANGING ON DOOR ] NEWLINE_TOKEN [ LANDLORD
BLEU score: 0.13397161259432624
ROUGE score: 0.4615384565680473
BERT F1 score: 0.4946404993534088
BERT Precision score: 0.474833220243454
BERT Recall score: 0.5134851336479187
Evaluating 11/200...
Seed: Germany broadcasting , NEWLINE_TOKEN Germany broadcasting . NEWLINE_TOKEN People of Britain , NEWLINE_TOKEN greetings from NEWLINE_TOKEN the Third Reich . NEWLINE_TOKEN This is the voice you NEWLINE_TOKEN have learned to fear . NEWLINE_TOKEN This is the NEWLINE_TOKEN Voice of Terror . NEWLINE_TOKEN Again , we bring NEWLINE_TOKEN you disaster
Candidate: on a daily basis . NEWLINE_TOKEN The weather forecast for the UK NEWLINE_TOKEN is now clear . NEWLINE_TOKEN The Storm Irene will bring NEWLINE_TOKEN heavy rainfall and dangerous wind . NEWLINE_
Reference: , NEWLINE_TOKEN crushing humiliating NEWLINE_TOKEN disaster . NEWLINE_TOKEN It is folly to NEWLINE_TOKEN stand against NEWLINE_TOKEN the mighty wraith NEWLINE_TOKEN of the Fuhrer . NEWLINE_TOKEN Do you need more testimony NEWLINE_TOKEN of his invincible might NEWLINE_TOKEN to bring you NEWLINE_TOKEN to your knees ? NEWLINE_TOKEN Very well
BLEU score: 0.02054935659395076
ROUGE score: 0.11111110617283973
BERT F1 score: 0.3246636390686035
BERT Precision score: 0.33331263065338135
BERT Recall score: 0.31456393003463745
Evaluating 12/200...
Seed: Thanks for coming early Tommy NEWLINE_TOKEN So , what happened this time ? NEWLINE_TOKEN I splitted up with my girl NEWLINE_TOKEN man ; Forget that bitch NEWLINE_TOKEN She is n't right NEWLINE_TOKEN man she wants me NEWLINE_TOKEN to be somebody I 'm not NEWLINE_TOKEN All her friends date a
Candidate: man NEWLINE_TOKEN He has sex twice a day NEWLINE_TOKEN They say she 's hot NEWLINE_TOKEN But I 'm a woman and I ca n't be anything else NEWLINE_TOKEN She has no clothes on
Reference: bunch NEWLINE_TOKEN of college boys and shit NEWLINE_TOKEN That is n't me . NEWLINE_TOKEN I got you . NEWLINE_TOKEN You NEWLINE_TOKEN know what I love about Miami ? NEWLINE_TOKEN Everybody is dirty NEWLINE_TOKEN And if you want NEWLINE_TOKEN to make some money you NEWLINE_TOKEN got to get dirty too .
BLEU score: 0.008629023997379932
ROUGE score: 0.10169491029014675
BERT F1 score: 0.3051168918609619
BERT Precision score: 0.3191833198070526
BERT Recall score: 0.2896135747432709
Evaluating 13/200...
Seed: Mathematicians NEWLINE_TOKEN won the war . NEWLINE_TOKEN Mathematicians broke NEWLINE_TOKEN the Japanese codes- NEWLINE_TOKEN and built the A-bomb . NEWLINE_TOKEN Mathematicians ... NEWLINE_TOKEN like you . NEWLINE_TOKEN The stated goal of the Soviets NEWLINE_TOKEN is global Communism . NEWLINE_TOKEN In medicine
Candidate: , at least , it is . NEWLINE_TOKEN The goal is ... to revolutionize NEWLINE_TOKEN the way we do NEWLINE_TOKEN our work . NEWLINE_TOKEN We can do it in 10 years time ,
Reference: or economics , NEWLINE_TOKEN in technology or space , NEWLINE_TOKEN battle lines are being drawn . NEWLINE_TOKEN To triumph , NEWLINE_TOKEN we need results- NEWLINE_TOKEN publishable , NEWLINE_TOKEN applicable results . NEWLINE_TOKEN Now who among you NEWLINE_TOKEN will be the next Morse ? NEWLINE_TOKEN The next Einstein ?
BLEU score: 0.02505431822984206
ROUGE score: 0.22222221739369008
BERT F1 score: 0.2873617708683014
BERT Precision score: 0.28638312220573425
BERT Recall score: 0.2867700159549713
Evaluating 14/200...
Seed: 1 NEWLINE_TOKEN [ theme music comes up NEWLINE_TOKEN with sound of gushing water ] NEWLINE_TOKEN [ sounds of waterfall ] NEWLINE_TOKEN Have you been up to the job site ? NEWLINE_TOKEN I honestly do n't think NEWLINE_TOKEN Tuesday is an option . NEWLINE_TOKEN I think if we
Candidate: went back to our previous NEWLINE_TOKEN plan , NEWLINE_TOKEN we could still lose our crew . NEWLINE_TOKEN [ cia clucking ] NEWLINE_TOKEN [ creaking ] NEWLINE_TOKEN [
Reference: do n't get NEWLINE_TOKEN it out there Monday ... NEWLINE_TOKEN So do you want to say NEWLINE_TOKEN Monday at noon ? NEWLINE_TOKEN I love it . NEWLINE_TOKEN Okay , have a great weekend . NEWLINE_TOKEN Thank you . NEWLINE_TOKEN [ whistling ] NEWLINE_TOKEN [ sounds of
BLEU score: 0.045068735047419525
ROUGE score: 0.20833332864583345
BERT F1 score: 0.44439369440078735
BERT Precision score: 0.491417795419693
BERT Recall score: 0.3970683515071869
Evaluating 15/200...
Seed: [ laughing ] NEWLINE_TOKEN Your usual . NEWLINE_TOKEN With ghost peppers and extra sriracha . NEWLINE_TOKEN Hooray ! My hot , hot dog . NEWLINE_TOKEN [ head whistles ] NEWLINE_TOKEN [ burps , panting ] NEWLINE_TOKEN Milk will put out that fire
Candidate: ! NEWLINE_TOKEN [ shouts ] NEWLINE_TOKEN [ sips ] NEWLINE_TOKEN What 's the matter ? NEWLINE_TOKEN I got a girl ! NEWLINE_TOKEN [ giggles ] NEWLINE_
Reference: . NEWLINE_TOKEN [ slurps ] NEWLINE_TOKEN [ sighs ] NEWLINE_TOKEN See you again tomorrow . NEWLINE_TOKEN [ laughs ] NEWLINE_TOKEN [ pants ] Give it ! NEWLINE_TOKEN Let go ! NEWLINE_TOKEN Oh , great ! Thanks a lot . NEWLINE_TOKEN Look what you did !
BLEU score: 0.046769782791500146
ROUGE score: 0.2380952332766441
BERT F1 score: 0.6004297137260437
BERT Precision score: 0.607478141784668
BERT Recall score: 0.5925233960151672
Evaluating 16/200...
Seed: 1 NEWLINE_TOKEN [ instrumental music ] NEWLINE_TOKEN [ upbeat music ] NEWLINE_TOKEN ( Kat ) Once up on a time there NEWLINE_TOKEN was a girl who loved Christmas . NEWLINE_TOKEN I mean what 's not to love ? NEWLINE_TOKEN Opening presents NEWLINE_TOKEN with her amazing family .
Candidate: NEWLINE_TOKEN And that was NEWLINE_TOKEN before I got into college . NEWLINE_TOKEN I remember sitting NEWLINE_TOKEN on the porch smoking NEWLINE_TOKEN and wondering what all the fuss was about .
Reference: Kissing her totally hot NEWLINE_TOKEN boyfriend under the mistletoe . NEWLINE_TOKEN But the tinsel on the tree .. NEWLINE_TOKEN ... she was an insanely-talented NEWLINE_TOKEN songwriter . NEWLINE_TOKEN Her music videos NEWLINE_TOKEN had over a billion views NEWLINE_TOKEN and her newest
BLEU score: 0.029233611576828147
ROUGE score: 0.20408162775510216
BERT F1 score: 0.2907487750053406
BERT Precision score: 0.30855995416641235
BERT Recall score: 0.27152231335639954
Evaluating 17/200...
Seed: Brandon . You 're not here NEWLINE_TOKEN to play games . Reset time ! Sir . Horse stance . Sir . Sir . Sir . -Class dismissed . NEWLINE_TOKEN Sir . Good job . All right now , baby . NEWLINE_TOKEN Let 's roll . Show us what you
Candidate: got . NEWLINE_TOKEN Sir . What you got ? NEWLINE_TOKEN Ouch . NEWLINE_TOKEN Oh . Ouch . NEWLINE_TOKEN Let 's see , let 'em stash it . NEWLINE_TO
Reference: got NEWLINE_TOKEN Show us what you got . Whoo ! What a way to start NEWLINE_TOKEN this thing off . Go , go . Oh , I see y'all . Hey . Lunge toss . NEWLINE_TOKEN Y'all gots to top that , baby
BLEU score: 0.028242431765747707
ROUGE score: 0.2916666620920139
BERT F1 score: 0.4190020263195038
BERT Precision score: 0.4979260563850403
BERT Recall score: 0.34134867787361145
Evaluating 18/200...
Seed: - Mr. Vale . NEWLINE_TOKEN - Yes . NEWLINE_TOKEN I 'm Barbara Watson . NEWLINE_TOKEN Yes . Come in . NEWLINE_TOKEN Thank you . NEWLINE_TOKEN Hmm . NEWLINE_TOKEN Ah . May I take your coat ? NEWLINE_TOKEN No , thank you . NEWLINE_TOKEN Uh ... NEWLINE_TOKEN would you like
Candidate: a double pepperoni pizza ? NEWLINE_TOKEN You ' ll be surprised NEWLINE_TOKEN if you don ' t have NEWLINE_TOKEN a tippy to dip . NEWLINE_TOKEN You ' ll be surprised NEWLINE
Reference: something to drink ? NEWLINE_TOKEN No . NEWLINE_TOKEN Shall we get started ? NEWLINE_TOKEN Uh , okay . NEWLINE_TOKEN Let 's try it again . NEWLINE_TOKEN The same thing ? NEWLINE_TOKEN Yes . NEWLINE_TOKEN And remember ... NEWLINE_TOKEN fingers curved like a tunnel . NEWLINE_TOKEN Okay . NEWLINE_TOKEN Do n't
BLEU score: 0.01811263350856297
ROUGE score: 0.11538461065088776
BERT F1 score: 0.35579225420951843
BERT Precision score: 0.32719773054122925
BERT Recall score: 0.3832961916923523
Evaluating 19/200...
Seed: I should have told her everything . NEWLINE_TOKEN Mom loved stories like that . NEWLINE_TOKEN MY LIFE AS A DOG NEWLINE_TOKEN It 's not so bad if you think about it . NEWLINE_TOKEN It could have been worse . NEWLINE_TOKEN Just think how that poor guy ended up NEWLINE_TOKEN
Candidate: in a hellhole like this . NEWLINE_TOKEN My name is Sidney Halloway and I 'm 18 years old . NEWLINE_TOKEN I live alone here with my mom and my grandmother . NEWLINE_TOKEN My mom tells me
Reference: who got a new kidney in Boston . NEWLINE_TOKEN He got his name in all the papers , NEWLINE_TOKEN but he died just the same . NEWLINE_TOKEN And what about Laika , the space dog ? NEWLINE_TOKEN They put her in a Sputnik NEWLINE_TOKEN and sent her
BLEU score: 0.024515815930430358
ROUGE score: 0.16949152049411104
BERT F1 score: 0.3255367875099182
BERT Precision score: 0.31811168789863586
BERT Recall score: 0.33149388432502747
Evaluating 20/200...
Seed: these fields NEWLINE_TOKEN were the bloody arena NEWLINE_TOKEN for the most terrible NEWLINE_TOKEN conflict in human history NEWLINE_TOKEN In 1913 , an alien NEWLINE_TOKEN invasion shook the world NEWLINE_TOKEN and hurled it into an NEWLINE_TOKEN unimaginable future . NEWLINE_TOKEN The next four years NEWLINE_TOKEN of ferocious combat NEWLINE_TOKEN has forever
Candidate: changed NEWLINE_TOKEN the course of history . NEWLINE_TOKEN We are here to see it through . NEWLINE_TOKEN To see that monster that NEWLINE_TOKEN tore apart the human heart NEWLINE_TOKEN That
Reference: marked this ground NEWLINE_TOKEN as the land of the vanished . NEWLINE_TOKEN We were fighting monsters . NEWLINE_TOKEN There was life NEWLINE_TOKEN beyond our planet . NEWLINE_TOKEN It went completely NEWLINE_TOKEN against everything NEWLINE_TOKEN I 'd been raised to believe . NEWLINE_TOKEN I 'm standing feet away NEWLINE_TOKEN from this
BLEU score: 0.03372435618933615
ROUGE score: 0.1785714238839287
BERT F1 score: 0.4573659598827362
BERT Precision score: 0.4837099015712738
BERT Recall score: 0.4301246106624603
Evaluating 21/200...
Seed: Have a good day , Mr Quentin . NEWLINE_TOKEN Right ... NEWLINE_TOKEN Shut up , asshole ! NEWLINE_TOKEN You suck your ice . NEWLINE_TOKEN Sun on the beach . NEWLINE_TOKEN I do n't give NEWLINE_TOKEN a fig . NEWLINE_TOKEN You 're talking to me ? NEWLINE_TOKEN Are you talking to
Candidate: me NEWLINE_TOKEN of all the time ? NEWLINE_TOKEN 'Cause I 'm a grown man . NEWLINE_TOKEN That doesn 't bother me . NEWLINE_TOKEN Shut up ! NEWLINE_TOKEN You
Reference: me ? NEWLINE_TOKEN - Bye , Tony . NEWLINE_TOKEN - Bye , Jos . NEWLINE_TOKEN See you later . NEWLINE_TOKEN Bye . NEWLINE_TOKEN Bye , buddy . NEWLINE_TOKEN See you later . NEWLINE_TOKEN See you later , kids . NEWLINE_TOKEN - Your laces , Zo . NEWLINE_TOKEN - Never
BLEU score: 0.019741021277013486
ROUGE score: 0.1578947318975071
BERT F1 score: 0.345674991607666
BERT Precision score: 0.30150172114372253
BERT Recall score: 0.3892149031162262
Evaluating 22/200...

## Hugging face Transformer (DistilGPT2)

https://huggingface.co/yroshan/moviescript

In [48]:
from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = "yroshan/moviescript"

tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token
model = AutoModelForCausalLM.from_pretrained(model_name)

In [49]:
def preprocess_text(text):
    text = re.sub(r"\n+", "\n", text)
    text = text.replace("\n", " NEWLINE_TOKEN ")
    text = re.sub(r"\s+", " ", text)
    return text.strip()

def tokenize_function(example):
    processed = [preprocess_text(script) for script in example["Script"]]
    encodings = tokenizer(processed, truncation=True, padding="longest", max_length=256)
    encodings["labels"] = encodings["input_ids"].copy()
    return encodings

tokenized_dataset = dataset.map(tokenize_function, batched=True, remove_columns=["Script"])
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

100%|██████████| 1/1 [00:12<00:00, 12.91s/ba]
100%|██████████| 1/1 [00:03<00:00,  3.33s/ba]

In [51]:
# Train the model (Arguments)
training_args = TrainingArguments(
    output_dir="./distil-gpt2-script",
    eval_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=1,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    num_train_epochs=10,
    logging_dir="./logs",
)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

In [52]:
# Initialize the Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["test"],
    tokenizer=tokenizer,
    data_collator=data_collator
)

/tmp/ipykernel_1635/4126412472.py:2: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [53]:
# Train the model
trainer.train()

# Save the model
trainer.save_model("./distil-gpt2-script")

In [54]:
from transformers import GPT2Tokenizer, GPT2LMHeadModel
import evaluate
import re
from bert_score import BERTScorer

# Load tokenizer and model
model = GPT2LMHeadModel.from_pretrained("./distil-gpt2-script")
tokenizer = GPT2Tokenizer.from_pretrained("./distil-gpt2-script")
model.eval()

# Metrics
scorer = BERTScorer(lang="en", model_type="roberta-base", rescale_with_baseline=True)

# Generation function
def generate_text(prompt, max_new_tokens=100):
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    outputs = model.generate(
        **inputs,
        max_new_tokens=max_new_tokens,
        do_sample=True,
        temperature=0.9,
        top_k=50,
        top_p=0.95,
        pad_token_id=tokenizer.eos_token_id
    )
    return tokenizer.decode(outputs[0], skip_special_tokens=True)

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [56]:
import re
from bert_score import BERTScorer

bleu_scores, rouge_scores = [], []
bert_f1, bert_precision, bert_recall = [], [], []

SCRIPT_LIMIT_TOKEN_SIZE = 50
GENERATE_LIMIT_TOKEN_SIZE = 50

total = len(test_texts)
i = 1

scorer = BERTScorer(lang="en", model_type="roberta-base", rescale_with_baseline=True)

print("Evaluating the model on the test set...")
for full_text in test_texts:
    print(f"Evaluating {i}/{total}...")

    tokenized = tokenizer(full_text, return_tensors="pt", truncation=True,
                          max_length=SCRIPT_LIMIT_TOKEN_SIZE + GENERATE_LIMIT_TOKEN_SIZE)
    input_ids = tokenized.input_ids[0]

    if len(input_ids) <= SCRIPT_LIMIT_TOKEN_SIZE:
        i += 1
        continue

    seed_input_ids = input_ids[:SCRIPT_LIMIT_TOKEN_SIZE]
    expected_output_ids = input_ids[SCRIPT_LIMIT_TOKEN_SIZE:SCRIPT_LIMIT_TOKEN_SIZE + GENERATE_LIMIT_TOKEN_SIZE]

    seed_text = tokenizer.decode(seed_input_ids, skip_special_tokens=True)
    seed_text = custom_tokenize(seed_text)
    seed_text = " ".join(seed_text)
    
    reference_text = tokenizer.decode(expected_output_ids, skip_special_tokens=True).strip()
    reference_text = custom_tokenize(reference_text)
    reference_text = " ".join(reference_text)

    generated_text = generate_text(seed_text, max_new_tokens=GENERATE_LIMIT_TOKEN_SIZE)
    generated_text = re.sub(r"\s+", " ", generated_text).strip()
    generated_text = custom_tokenize(generated_text)
    generated_text = " ".join(generated_text)[len(seed_text) + 1:]

    candidate = generated_text
    reference = reference_text

    print(f"Seed: {seed_text}")
    print(f"Candidate: {candidate}")
    print(f"Reference: {reference}")
    
    bleu_score, rouge_score = calculate_scores(reference, candidate)

    P, R, F1 = scorer.score([candidate], [reference])
    f1_score = F1.mean().item()
    precision_score = P.mean().item()
    recall_score = R.mean().item()

    bleu_scores.append(bleu_score)
    rouge_scores.append(rouge_score)
    bert_f1.append(f1_score)
    bert_precision.append(precision_score)
    bert_recall.append(recall_score)

    print(f"BLEU score: {bleu_score}")
    print(f"ROUGE score: {rouge_score}")
    print(f"BERT F1 score: {f1_score}")
    print(f"BERT Precision score: {precision_score}")
    print(f"BERT Recall score: {recall_score}")

    with open(f"transformers-distilGPT2-{SCRIPT_LIMIT_TOKEN_SIZE}-{GENERATE_LIMIT_TOKEN_SIZE}.csv", "a") as f:
        f.write(f"{seed_text};{candidate};{reference};{bleu_score};{rouge_score};{f1_score};{precision_score};{recall_score}\n")

    i += 1

print(f"Average BLEU score : {sum(bleu_scores) / len(bleu_scores):.6f}")
print(f"Average ROUGE score : {sum(rouge_scores) / len(rouge_scores):.6f}")
print(f"Average BERT F1 score : {sum(bert_f1) / len(bert_f1):.6f}")
print(f"Average BERT Precision score : {sum(bert_precision) / len(bert_precision):.6f}")
print(f"Average BERT Recall score : {sum(bert_recall) / len(bert_recall):.6f}")

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Evaluating the model on the test set...
Evaluating 1/200...
Seed: 1 NEWLINE_TOKEN Delhi flight ! NEWLINE_TOKEN Sorry , Ma'am . NEWLINE_TOKEN Boarding is closed . NEWLINE_TOKEN Listen , I know ! NEWLINE_TOKEN I am so sorry , I got delayed . NEWLINE_TOKEN Just do something . NEWLINE_TOKEN Please help me . NEWLINE_TOKEN Sorry , Ma'am
Candidate: . NEWLINE_TOKEN I am so sorry . NEWLINE_TOKEN Sorry , ma'am . NEWLINE_TOKEN I know I have worked . NEWLINE_TOKEN Please help me . NEWLINE_TOKEN Please help me
Reference: . NEWLINE_TOKEN You should have been on time . NEWLINE_TOKEN I know , I am so sorry ! NEWLINE_TOKEN I got stuck in traffic . NEWLINE_TOKEN You know how it is . NEWLINE_TOKEN Just , please ! Can you do this ? NEWLINE_TOKEN Okay , hold on . NEWLINE_TOKEN Thank
BLEU score: 0.11008265656260736
ROUGE score: 0.35555555126913585
BERT F1 score: 0.617845892906189
BERT Precision score: 0.6659048795700073
BERT Recall score: 0.5698670148849487
Evaluating 2/200...
Seed: He 's going to end corruption . NEWLINE_TOKEN Gannu is here to rule . NEWLINE_TOKEN He 's going to end corruption . NEWLINE_TOKEN Gannu is here to rule . NEWLINE_TOKEN He 's going to end corruption . NEWLINE_TOKEN Gannu is here to rule .
Candidate: NEWLINE_TOKEN He 's going to end corruption . NEWLINE_TOKEN Gannu is here to rule . NEWLINE_TOKEN Gannu is here to rule . NEWLINE_TOKEN Now , do not run .
Reference: He 's going to end corruption . NEWLINE_TOKEN Calm down . NEWLINE_TOKEN Please calm down ! NEWLINE_TOKEN Please calm down ! NEWLINE_TOKEN This is not just you speaking up . NEWLINE_TOKEN It is the entire nation revolting ... NEWLINE_TOKEN against its pathetic plight . NEWLINE_TOKEN But the time
BLEU score: 0.15557582835359607
ROUGE score: 0.3913043432892249
BERT F1 score: 0.4656026065349579
BERT Precision score: 0.4874226450920105
BERT Recall score: 0.44281139969825745
Evaluating 3/200...
Seed: Come on , I 'm open ! NEWLINE_TOKEN Naty , over here ! NEWLINE_TOKEN Give me that . NEWLINE_TOKEN We were just ... NEWLINE_TOKEN Pass ! NEWLINE_TOKEN Here ! Over here ! NEWLINE_TOKEN Is someone else NEWLINE_TOKEN gon na turn Priscilla ? NEWLINE_TOKEN Me , too ! I
Candidate: want you to go ! NEWLINE_TOKEN I want to go ! NEWLINE_TOKEN I want to go ! NEWLINE_TOKEN Priscilla 's not doing well . NEWLINE_TOKEN So I 'll keep her at home
Reference: 'm open ! NEWLINE_TOKEN Come on , I 'm open ! NEWLINE_TOKEN Pass it ! NEWLINE_TOKEN Amanda , here ! NEWLINE_TOKEN How about Wes ? NEWLINE_TOKEN How 's he doing ? NEWLINE_TOKEN He 's still Wes . NEWLINE_TOKEN He has no friends , really . NEWLINE_TOKEN Just kind of on
BLEU score: 0.023834444016038046
ROUGE score: 0.2173912995841211
BERT F1 score: 0.5046601295471191
BERT Precision score: 0.4911305904388428
BERT Recall score: 0.5171668529510498
Evaluating 4/200...
Seed: 1 NEWLINE_TOKEN [ ambient music ] NEWLINE_TOKEN [ audience applauding ] NEWLINE_TOKEN Here in New York , NEWLINE_TOKEN there 's a big election tomorrow . NEWLINE_TOKEN The city will be choosing NEWLINE_TOKEN a new mayor that many ... NEWLINE_TOKEN [ audience cheering ] NEWLINE_TOKEN ... that
Candidate: has already been forecast . NEWLINE_TOKEN The race has just begun . NEWLINE_TOKEN [ Bernie Sanders ] NEWLINE_TOKEN [ Bernie Sanders ] NEWLINE_TOKEN I 'm hoping the change in the direction NEWLINE_
Reference: many are calling NEWLINE_TOKEN `` Not Bill de Blasio . '' NEWLINE_TOKEN [ audience laughs ] NEWLINE_TOKEN New York will also be electing NEWLINE_TOKEN a new city council , NEWLINE_TOKEN and there 's some shocking news NEWLINE_TOKEN out of that race . NEWLINE_TOKEN Manhattan candidate NEWLINE_TOKEN Zack Weiner --
BLEU score: 0.02176479094893621
ROUGE score: 0.1311475364686914
BERT F1 score: 0.4155906140804291
BERT Precision score: 0.44374436140060425
BERT Recall score: 0.3864922523498535
Evaluating 5/200...
Seed: Moving onto the Hollywood Freeway , NEWLINE_TOKEN we have a multiple vehicle ... NEWLINE_TOKEN multiple injury accident . NEWLINE_TOKEN An absolute mess NEWLINE_TOKEN from VineStreet to the valley . NEWLINE_TOKEN If you 're in it , NEWLINE_TOKEN expect a long commute . NEWLINE_TOKEN If you 're not ,
Candidate: NEWLINE_TOKEN keep your eye on the signs NEWLINE_TOKEN and keep your eyes peeled . NEWLINE_TOKEN Do not drive too far NEWLINE_TOKEN and leave your windows on the side NEWLINE_TOKEN when
Reference: seek alternate routes . NEWLINE_TOKEN If Dan doesn 't want to do a daily rate , NEWLINE_TOKEN we can talk about a weekly rate . NEWLINE_TOKEN But I 'm tellin ' you right now , NEWLINE_TOKEN I 'm not goin ' below a million .
BLEU score: 0.016347025072668595
ROUGE score: 0.07843136787389493
BERT F1 score: 0.2803002595901489
BERT Precision score: 0.3617098927497864
BERT Recall score: 0.2001027762889862
Evaluating 6/200...
Seed: And I 'll start it up ... NEWLINE_TOKEN ... and we 'll start generating . NEWLINE_TOKEN John has a very special mission in life . NEWLINE_TOKEN He is trying to contact aliens . NEWLINE_TOKEN It was started by myself . NEWLINE_TOKEN My grandfather helped me . NEWLINE_TOKEN I lived with
Candidate: my grandfather , Charles Darwin . NEWLINE_TOKEN When I was a boy , NEWLINE_TOKEN he looked like he was going to pick up a man . NEWLINE_TOKEN I was scared and scared . NEWLINE_TOKEN
Reference: my grandparents NEWLINE_TOKEN in a small cottage in Northern Michigan . NEWLINE_TOKEN I started building NEWLINE_TOKEN the electronic equipment to make contact NEWLINE_TOKEN with whatever might be out there NEWLINE_TOKEN beyond the Earth . NEWLINE_TOKEN It grew to encompass an entire bedroom . NEWLINE_TOKEN That equipment continued to grow .
BLEU score: 0.03816759900607165
ROUGE score: 0.1785714238839287
BERT F1 score: 0.3836434483528137
BERT Precision score: 0.3998486399650574
BERT Recall score: 0.3661993145942688
Evaluating 7/200...
Seed: 1 NEWLINE_TOKEN 'It is said that Heer and Ranjha NEWLINE_TOKEN made TakhtHazaare popular . ' NEWLINE_TOKEN 'Sohni-Mehiwal made NEWLINE_TOKEN river Chenab popular . ' NEWLINE_TOKEN 'Romeo and Juliet made Italy popular . ' NEWLINE_TOKEN
Candidate: to made Ito 's 'Mumbai ' was the NEWLINE_TOKEN most popular place in the country . NEWLINE_TOKEN 'Rescue ' . NEWLINE_TOKEN 'Rescue ' . NEWLINE_TOKEN
Reference: 'But this is not Italy . NEWLINE_TOKEN This is Patiala , my city . ' NEWLINE_TOKEN 'Now even this will become NEWLINE_TOKEN popular in the entire world . ' NEWLINE_TOKEN 'Because of my love story . ' NEWLINE_TOKEN Laali , what are you doing dear ?
BLEU score: 0.019813223705011554
ROUGE score: 0.21276595310095073
BERT F1 score: 0.3347140848636627
BERT Precision score: 0.37847939133644104
BERT Recall score: 0.29030823707580566
Evaluating 8/200...
Seed: Pay attention to the sights , NEWLINE_TOKEN and not the words . NEWLINE_TOKEN Because sounds can NEWLINE_TOKEN often be deceptive . NEWLINE_TOKEN But sight ... NEWLINE_TOKEN Sights never lie . NEWLINE_TOKEN So the question is not NEWLINE_TOKEN what is in front of your eyes . NEWLINE_TOKEN The question is
Candidate: what is in front of your eyes . NEWLINE_TOKEN And if you turn your back on those sights , NEWLINE_TOKEN the very things that surround you . NEWLINE_TOKEN How do you know that . NEWLINE_TO
Reference: what NEWLINE_TOKEN are you looking at ? NEWLINE_TOKEN David , my brother . NEWLINE_TOKEN How are you ? NEWLINE_TOKEN All good , man . NEWLINE_TOKEN Hand it over . NEWLINE_TOKEN Next time you got to be here earlier . NEWLINE_TOKEN You ca n't keep me waiting like this .
BLEU score: 0.0378682855637289
ROUGE score: 0.16949152049411104
BERT F1 score: 0.31049469113349915
BERT Precision score: 0.28715789318084717
BERT Recall score: 0.33252912759780884
Evaluating 9/200...
Seed: This is my recurring dream NEWLINE_TOKEN That I am fIying .. NEWLINE_TOKEN .. Iike a bird .. in the sky NEWLINE_TOKEN Cutting through the cIouds NEWLINE_TOKEN And when I am fIying .. I feeI happy NEWLINE_TOKEN A happiness that is NEWLINE_TOKEN
Candidate: A world in which I can sing and sing NEWLINE_TOKEN And yet the cIouds are still waiting for me NEWLINE_TOKEN to sing NEWLINE_TOKEN and then I get bogged down in nonsense NEWLINE_
Reference: impossibIe to describe NEWLINE_TOKEN A feeIing Iike nothing NEWLINE_TOKEN eIse - Unique ... wondrous NEWLINE_TOKEN But this is not a dream- this is reaI NEWLINE_TOKEN The wind that caresses my face NEWLINE_TOKEN The sound of g
BLEU score: 0.011628456214744225
ROUGE score: 0.07547169312922783
BERT F1 score: 0.19937264919281006
BERT Precision score: 0.20957303047180176
BERT Recall score: 0.18746167421340942
Evaluating 10/200...
Seed: [ EERIE MUSIC PLAYING ] NEWLINE_TOKEN [ KNOCKING ON DOOR ] NEWLINE_TOKEN [ LANDLORD ] Father ! NEWLINE_TOKEN [ KNOCKING ON DOOR ] NEWLINE_TOKEN [ LANDLORD ] NEWLINE_TOKEN Open the door , Father ! NEWLINE_TOKEN [
Candidate: NEWLINE_TOKEN WOMAN WHOOSHING ] NEWLINE_TOKEN [ VOICES CLANG ] NEWLINE_TOKEN [ VOICES LATER ] NEWLINE_TOKEN [ VOICES RATING ] NEWLINE_TOKEN
Reference: BANGING ON DOOR ] NEWLINE_TOKEN [ LANDLORD ] Father ! NEWLINE_TOKEN Father ! NEWLINE_TOKEN [ DOOR RATTLING ] NEWLINE_TOKEN [ LANDLORD ] My god ! NEWLINE_TOKEN [ BANGING ON DOOR ] NEWLINE_TOKEN [ LANDLORD
BLEU score: 0.07627053525722971
ROUGE score: 0.2857142808163266
BERT F1 score: 0.4999527633190155
BERT Precision score: 0.5686530470848083
BERT Recall score: 0.4320603311061859
Evaluating 11/200...
Seed: Germany broadcasting , NEWLINE_TOKEN Germany broadcasting . NEWLINE_TOKEN People of Britain , NEWLINE_TOKEN greetings from NEWLINE_TOKEN the Third Reich . NEWLINE_TOKEN This is the voice you NEWLINE_TOKEN have learned to fear . NEWLINE_TOKEN This is the NEWLINE_TOKEN Voice of Terror . NEWLINE_TOKEN Again , we bring NEWLINE_TOKEN you disaster
Candidate: news . NEWLINE_TOKEN This is the voice you have heard before . NEWLINE_TOKEN This is the voice you have heard before . NEWLINE_TOKEN This is the voice you have heard before . NEWLINE_TOKEN This
Reference: , NEWLINE_TOKEN crushing humiliating NEWLINE_TOKEN disaster . NEWLINE_TOKEN It is folly to NEWLINE_TOKEN stand against NEWLINE_TOKEN the mighty wraith NEWLINE_TOKEN of the Fuhrer . NEWLINE_TOKEN Do you need more testimony NEWLINE_TOKEN of his invincible might NEWLINE_TOKEN to bring you NEWLINE_TOKEN to your knees ? NEWLINE_TOKEN Very well
BLEU score: 0.022715987557673116
ROUGE score: 0.19999999625000006
BERT F1 score: 0.31535977125167847
BERT Precision score: 0.32671624422073364
BERT Recall score: 0.3025573194026947
Evaluating 12/200...
Seed: Thanks for coming early Tommy NEWLINE_TOKEN So , what happened this time ? NEWLINE_TOKEN I splitted up with my girl NEWLINE_TOKEN man ; Forget that bitch NEWLINE_TOKEN She is n't right NEWLINE_TOKEN man she wants me NEWLINE_TOKEN to be somebody I 'm not NEWLINE_TOKEN All her friends date a
Candidate: guy . NEWLINE_TOKEN But I 'm not really that into here NEWLINE_TOKEN Why ? NEWLINE_TOKEN I was in a relationship with a girl who has NEWLINE_TOKEN had a hard time dating her . NEW
Reference: bunch NEWLINE_TOKEN of college boys and shit NEWLINE_TOKEN That is n't me . NEWLINE_TOKEN I got you . NEWLINE_TOKEN You NEWLINE_TOKEN know what I love about Miami ? NEWLINE_TOKEN Everybody is dirty NEWLINE_TOKEN And if you want NEWLINE_TOKEN to make some money you NEWLINE_TOKEN got to get dirty too .
BLEU score: 0.021890051918546018
ROUGE score: 0.0689655122948874
BERT F1 score: 0.38541194796562195
BERT Precision score: 0.37759846448898315
BERT Recall score: 0.39189156889915466
Evaluating 13/200...
Seed: Mathematicians NEWLINE_TOKEN won the war . NEWLINE_TOKEN Mathematicians broke NEWLINE_TOKEN the Japanese codes- NEWLINE_TOKEN and built the A-bomb . NEWLINE_TOKEN Mathematicians ... NEWLINE_TOKEN like you . NEWLINE_TOKEN The stated goal of the Soviets NEWLINE_TOKEN is global Communism . NEWLINE_TOKEN In medicine
Candidate: we are trained to NEWLINE_TOKEN abstract concepts from concepts like numbers . NEWLINE_TOKEN Mathematicians are trained to formulate NEWLINE_TOKEN their own rules . NEWLINE_TOKEN Mathematicians are trained to construct NEW
Reference: or economics , NEWLINE_TOKEN in technology or space , NEWLINE_TOKEN battle lines are being drawn . NEWLINE_TOKEN To triumph , NEWLINE_TOKEN we need results- NEWLINE_TOKEN publishable , NEWLINE_TOKEN applicable results . NEWLINE_TOKEN Now who among you NEWLINE_TOKEN will be the next Morse ? NEWLINE_TOKEN The next Einstein ?
BLEU score: 0.018901726012315465
ROUGE score: 0.12244897506039165
BERT F1 score: 0.2758505642414093
BERT Precision score: 0.2619372606277466
BERT Recall score: 0.2882416546344757
Evaluating 14/200...
Seed: 1 NEWLINE_TOKEN [ theme music comes up NEWLINE_TOKEN with sound of gushing water ] NEWLINE_TOKEN [ sounds of waterfall ] NEWLINE_TOKEN Have you been up to the job site ? NEWLINE_TOKEN I honestly do n't think NEWLINE_TOKEN Tuesday is an option . NEWLINE_TOKEN I think if we
Candidate: had NEWLINE_TOKEN a choice , then we 'd have NEWLINE_TOKEN decided to close the NEWLINE_TOKEN bakery and put our NEWLINE_TOKEN family and friends NEWLINE_TOKEN through the process . NEWLINE
Reference: do n't get NEWLINE_TOKEN it out there Monday ... NEWLINE_TOKEN So do you want to say NEWLINE_TOKEN Monday at noon ? NEWLINE_TOKEN I love it . NEWLINE_TOKEN Okay , have a great weekend . NEWLINE_TOKEN Thank you . NEWLINE_TOKEN [ whistling ] NEWLINE_TOKEN [ sounds of
BLEU score: 0.009465177264453003
ROUGE score: 0.1538461489644972
BERT F1 score: 0.32583844661712646
BERT Precision score: 0.36867454648017883
BERT Recall score: 0.2823100686073303
Evaluating 15/200...
Seed: [ laughing ] NEWLINE_TOKEN Your usual . NEWLINE_TOKEN With ghost peppers and extra sriracha . NEWLINE_TOKEN Hooray ! My hot , hot dog . NEWLINE_TOKEN [ head whistles ] NEWLINE_TOKEN [ burps , panting ] NEWLINE_TOKEN Milk will put out that fire
Candidate: . NEWLINE_TOKEN - Oh maw , thank you . NEWLINE_TOKEN - [ growling ] NEWLINE_TOKEN Oh I see that dog barking NEWLINE_TOKEN in the middle of the night . NEWLINE_
Reference: . NEWLINE_TOKEN [ slurps ] NEWLINE_TOKEN [ sighs ] NEWLINE_TOKEN See you again tomorrow . NEWLINE_TOKEN [ laughs ] NEWLINE_TOKEN [ pants ] Give it ! NEWLINE_TOKEN Let go ! NEWLINE_TOKEN Oh , great ! Thanks a lot . NEWLINE_TOKEN Look what you did !
BLEU score: 0.02749230956733923
ROUGE score: 0.26086956025519853
BERT F1 score: 0.45367828011512756
BERT Precision score: 0.4097769856452942
BERT Recall score: 0.49715977907180786
Evaluating 16/200...
Seed: 1 NEWLINE_TOKEN [ instrumental music ] NEWLINE_TOKEN [ upbeat music ] NEWLINE_TOKEN ( Kat ) Once up on a time there NEWLINE_TOKEN was a girl who loved Christmas . NEWLINE_TOKEN I mean what 's not to love ? NEWLINE_TOKEN Opening presents NEWLINE_TOKEN with her amazing family .
Candidate: NEWLINE_TOKEN And then there was Mandy and Dad . NEWLINE_TOKEN And then there was the wonderful Ann and Tommy who NEWLINE_TOKEN would never forget . NEWLINE_TOKEN And then there was the lovely Maggie
Reference: Kissing her totally hot NEWLINE_TOKEN boyfriend under the mistletoe . NEWLINE_TOKEN But the tinsel on the tree .. NEWLINE_TOKEN ... she was an insanely-talented NEWLINE_TOKEN songwriter . NEWLINE_TOKEN Her music videos NEWLINE_TOKEN had over a billion views NEWLINE_TOKEN and her newest
BLEU score: 0.026211809829989424
ROUGE score: 0.1739130387145559
BERT F1 score: 0.2723177373409271
BERT Precision score: 0.2683236300945282
BERT Recall score: 0.274711936712265
Evaluating 17/200...
Seed: Brandon . You 're not here NEWLINE_TOKEN to play games . Reset time ! Sir . Horse stance . Sir . Sir . Sir . -Class dismissed . NEWLINE_TOKEN Sir . Good job . All right now , baby . NEWLINE_TOKEN Let 's roll . Show us what you
Candidate: can do , sir . NEWLINE_TOKEN Good job sir . Sir . Can you play a bit more ? NEWLINE_TOKEN Yes sir . No . NEWLINE_TOKEN Please . NEWLINE_TOKEN Let 's play on
Reference: got NEWLINE_TOKEN Show us what you got . Whoo ! What a way to start NEWLINE_TOKEN this thing off . Go , go . Oh , I see y'all . Hey . Lunge toss . NEWLINE_TOKEN Y'all gots to top that , baby
BLEU score: 0.02171270557409236
ROUGE score: 0.15384614903106522
BERT F1 score: 0.34095123410224915
BERT Precision score: 0.415397584438324
BERT Recall score: 0.26737046241760254
Evaluating 18/200...
Seed: - Mr. Vale . NEWLINE_TOKEN - Yes . NEWLINE_TOKEN I 'm Barbara Watson . NEWLINE_TOKEN Yes . Come in . NEWLINE_TOKEN Thank you . NEWLINE_TOKEN Hmm . NEWLINE_TOKEN Ah . May I take your coat ? NEWLINE_TOKEN No , thank you . NEWLINE_TOKEN Uh ... NEWLINE_TOKEN would you like
Candidate: it ? NEWLINE_TOKEN Yes , thank you . NEWLINE_TOKEN I 'm sure you like it . NEWLINE_TOKEN Thank you . NEWLINE_TOKEN Is she at the wedding ? NEWLINE_TOKEN Yes .
Reference: something to drink ? NEWLINE_TOKEN No . NEWLINE_TOKEN Shall we get started ? NEWLINE_TOKEN Uh , okay . NEWLINE_TOKEN Let 's try it again . NEWLINE_TOKEN The same thing ? NEWLINE_TOKEN Yes . NEWLINE_TOKEN And remember ... NEWLINE_TOKEN fingers curved like a tunnel . NEWLINE_TOKEN Okay . NEWLINE_TOKEN Do n't
BLEU score: 0.06863014351352716
ROUGE score: 0.24489795465222827
BERT F1 score: 0.5295406579971313
BERT Precision score: 0.5455338954925537
BERT Recall score: 0.5126216411590576
Evaluating 19/200...
Seed: I should have told her everything . NEWLINE_TOKEN Mom loved stories like that . NEWLINE_TOKEN MY LIFE AS A DOG NEWLINE_TOKEN It 's not so bad if you think about it . NEWLINE_TOKEN It could have been worse . NEWLINE_TOKEN Just think how that poor guy ended up NEWLINE_TOKEN
Candidate: in a coma . NEWLINE_TOKEN I 've lost two of my favorite memories NEWLINE_TOKEN and it 's hard to believe NEWLINE_TOKEN just how far back NEWLINE_TOKEN I 've traveled . NEWLINE_TO
Reference: who got a new kidney in Boston . NEWLINE_TOKEN He got his name in all the papers , NEWLINE_TOKEN but he died just the same . NEWLINE_TOKEN And what about Laika , the space dog ? NEWLINE_TOKEN They put her in a Sputnik NEWLINE_TOKEN and sent her
BLEU score: 0.023348576930493463
ROUGE score: 0.17543859161588196
BERT F1 score: 0.3432556092739105
BERT Precision score: 0.35944312810897827
BERT Recall score: 0.32574209570884705
Evaluating 20/200...
Seed: these fields NEWLINE_TOKEN were the bloody arena NEWLINE_TOKEN for the most terrible NEWLINE_TOKEN conflict in human history NEWLINE_TOKEN In 1913 , an alien NEWLINE_TOKEN invasion shook the world NEWLINE_TOKEN and hurled it into an NEWLINE_TOKEN unimaginable future . NEWLINE_TOKEN The next four years NEWLINE_TOKEN of ferocious combat NEWLINE_TOKEN has forever
Candidate: left the Earth NEWLINE_TOKEN scarred by uncontrolled uncontrolled flow . NEWLINE_TOKEN In many ways , the events that led NEWLINE_TOKEN these events may have NEWLINE_TOKEN changed the course of history . NEWLINE
Reference: marked this ground NEWLINE_TOKEN as the land of the vanished . NEWLINE_TOKEN We were fighting monsters . NEWLINE_TOKEN There was life NEWLINE_TOKEN beyond our planet . NEWLINE_TOKEN It went completely NEWLINE_TOKEN against everything NEWLINE_TOKEN I 'd been raised to believe . NEWLINE_TOKEN I 'm standing feet away NEWLINE_TOKEN from this
BLEU score: 0.016028854396884434
ROUGE score: 0.06896551245541056
BERT F1 score: 0.37498530745506287
BERT Precision score: 0.3713909089565277
BERT Recall score: 0.3772050738334656
Evaluating 21/200...
Seed: Have a good day , Mr Quentin . NEWLINE_TOKEN Right ... NEWLINE_TOKEN Shut up , asshole ! NEWLINE_TOKEN You suck your ice . NEWLINE_TOKEN Sun on the beach . NEWLINE_TOKEN I do n't give NEWLINE_TOKEN a fig . NEWLINE_TOKEN You 're talking to me ? NEWLINE_TOKEN Are you talking to
Candidate: me ? NEWLINE_TOKEN Are you talking to me ? NEWLINE_TOKEN Are you talking to me ? NEWLINE_TOKEN You 're talking to me ? NEWLINE_TOKEN Are you talking to me ? NEWLINE_
Reference: me ? NEWLINE_TOKEN - Bye , Tony . NEWLINE_TOKEN - Bye , Jos . NEWLINE_TOKEN See you later . NEWLINE_TOKEN Bye . NEWLINE_TOKEN Bye , buddy . NEWLINE_TOKEN See you later . NEWLINE_TOKEN See you later , kids . NEWLINE_TOKEN - Your laces , Zo . NEWLINE_TOKEN - Never
BLEU score: 0.02992864538572248
ROUGE score: 0.2962962916323732